[env:lolin_c3_mini]
platform = espressif32
board = lolin_c3_mini
framework = arduino
monitor_speed = 115200

# Автоматичне завантаження потрібних бібліотек
lib_deps =
    https://github.com/tzapu/WiFiManager.git
    bblanchon/ArduinoJson @ ^6.21.3

# Налаштування файлової системи
board_build.filesystem = spiffs
board_build.partitions = default_4MB.csv
