[env:lolin_c3_mini]
platform = espressif32
board = lolin_c3_mini
framework = arduino
monitor_speed = 115200

# Повний набір бібліотек із підтримкою ESP32-C3
lib_deps =
    https://github.com/tzapu/WiFiManager.git
    bblanchon/ArduinoJson @ ^6.21.3
    https://github.com/mathieucarbou/ESPAsyncWebServer.git
    https://github.com/mathieucarbou/AsyncTCP.git

# Налаштування файлової системи
board_build.filesystem = spiffs
board_build.partitions = default_4MB.csv
